### PR TITLE
Refactoring neutron and nova to subpath

### PR DESCRIPTION
**Pull request by DTadrzak**

### CODE REVIEW

**Comment by Quentin-M** [comment]
To be tested on rkt.

**Comment by Quentin-M** [comment]
Fails on rkt with the nova-libvirt pod, which is the only one in the project that uses rkt fly: https://github.com/kubernetes/kubernetes/issues/34846

**Comment by DTadrzak** [comment]
@ss7pro 
@PiotrProkop 
@Quentin-M

**Comment by PiotrProkop** [comment]
LGTM

**Pull request merged**
