### PR TITLE
Check if mariadb.pid already exists and whether kolla_security_reset's been executed or not

### PR DESCRIPTION
**Pull request by tczekajlo**
In case when We've only one instance of MariaDB and container will be restarted then there is an issue with permissions. We've already set up data dir, thus when kolla_security_reset script is executed again we can see prompt which ask about root password, also mariadb.pid file already exists and the script is skipping sleep, so the script execute the line with grant privileges too fast, during when
database is not ready to handle query.

### CODE REVIEW

**Comment by Quentin-M** [comment]
Thank you for submitting the very first external contribution to Stackanetes!

The two-nodes use-case of Stackanetes is indeed quite important to us and therefore your fix is much welcomed. I believe that either @mateusz-blaszkowski or @ss7pro can review this?

**Comment by ss7pro** [comment]
@tczekajlo Thanks for your report. I would prefer to have that logic moved to start.sh. So we would detect if this is the first run and we need to bootstrap. What do you think ?

**Comment by ss7pro** [comment]
I have created a new one: https://github.com/stackanetes/stackanetes/pull/128

**Comment by tczekajlo** [comment]
Sure, the start.sh seems more suitable for this logic.

**Pull request closed without merging**
