### PR TITLE
Don't use fqdn in arguments for etcd

### PR DESCRIPTION
**Pull request by tczekajlo**
It seems alpine (musl) has an issue with domain resolve. In the case when in the resolv.conf is placed ndots:5 option and there is appended some.fancy.domain to search from our node then it is not possible to resolve absolute domain and etcd cluster cannot be established.

```
~ # kubectl --namespace=openstack exec etcd-1-24196704-fkq3j -t -i -- sh
/ # cat /etc/resolv.conf 
search openstack.svc.cluster.local svc.cluster.local cluster.local our.fancy.domain
nameserver 10.3.0.10
options ndots:5
/ # nslookup etcd-1.openstack.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'etcd-1.openstack.svc.cluster.local': Try again

/ # etcdctl cluster-health
failed to check the health of member 182bbad2c9e7c809 on http://etcd-1.openstack.svc.cluster.local:2379: Get http://etcd-1.openstack.svc.cluster.local:2379/health: dial tcp: i/o timeout
failed to check the health of member 182bbad2c9e7c809 on https://etcd-1.openstack.svc.cluster.local:4001: Get https://etcd-1.openstack.svc.cluster.local:4001/health: dial tcp: i/o timeout
member 182bbad2c9e7c809 is unreachable: [http://etcd-1.openstack.svc.cluster.local:2379 https://etcd-1.openstack.svc.cluster.local:4001] are all unreachable
failed to check the health of member c5350719ccc85301 on http://etcd-3.openstack.svc.cluster.local:2379: Get http://etcd-3.openstack.svc.cluster.local:2379/health: dial tcp: i/o timeout
failed to check the health of member c5350719ccc85301 on https://etcd-3.openstack.svc.cluster.local:4001: Get https://etcd-3.openstack.svc.cluster.local:4001/health: dial tcp: i/o timeout
member c5350719ccc85301 is unreachable: [http://etcd-3.openstack.svc.cluster.local:2379 https://etcd-3.openstack.svc.cluster.local:4001] are all unreachable
member e34f2fca9368a5ce is unreachable: no available published client urls
cluster is unhealthy
```

### CODE REVIEW

**Comment by ss7pro** [comment]
@tczekajlo Which k8s version are you running ? In our case it looks like this:

core@gklab-96a-104 ~ $ kubectl exec -ti etcd-1-1688537227-1l2jp sh
/ # cat /etc/resolv.conf 
search default.svc.cluster.local svc.cluster.local cluster.local igk.intel.com
nameserver 10.2.0.10
options ndots:5
/ # nslookup etcd-2.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      etcd-2.default.svc.cluster.local
Address 1: 10.2.100.215 etcd-2.default.svc.cluster.local
/ # nslookup etcd-3.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      etcd-3.default.svc.cluster.local
Address 1: 10.2.229.82 etcd-3.default.svc.cluster.local
/ # nslookup etcd-1.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      etcd-1.default.svc.cluster.local
Address 1: 10.2.40.118 etcd-1.default.svc.cluster.local
/ #

**Comment by ss7pro** [comment]
Alpine is known to not support search in resolv.conf, that's why full names needs to be used.

**Comment by tczekajlo** [comment]
Number of version which I use.

```
~ # kubectl version  
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+coreos.2", GitCommit:"672d0ab602ada99c100e7f18ecbbdcea181ef008", GitTreeState:"clean", BuildDate:"2016-09-30T05:49:34Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

~ # docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   1f8f545
 Built:        
 OS/Arch:      linux/amd64
```

Also example how it looks when I don't use fqdn.

```
/ # cat /etc/resolv.conf 
search openstack.svc.cluster.local svc.cluster.local cluster.local our.fancy.domain
nameserver 10.3.0.10
options ndots:5
/ # nslookup etcd-3.openstack
nslookup: can't resolve '(null)': Name does not resolve

Name:      etcd-3.openstack
Address 1: 10.3.0.77 etcd-3.openstack.svc.cluster.local
```

**Comment by ss7pro** [comment]
@Quentin-M Do you have K8S 1.4 by your hand so you can validate this behavior on K8S 1.4 ?

**Comment by ss7pro** [comment]
@tczekajlo Can you give us output of this command: kubectl --namespace=kube-system describe rc kube-dns

**Comment by tczekajlo** [comment]
@ss7pro It seems I've found the problem. If domain in search doesn't exists or SkyDNS can't forward request further then this issue appear. Thanks for your hint ;)

**Comment by Quentin-M** [comment]
@ss7pro @tczekajlo No issue with rkt and Kubernetes 1.4 with the etcd cluster. Also Alpine supports search domains since [3.4.0](https://alpinelinux.org/posts/Alpine-3.4.0-released.html) or edge (February/March).

```
$ rkt enter 0ddca32a nslookup etcd-1.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      etcd-1.default.svc.cluster.local
Address 1: 10.3.0.22 etcd-1.default.svc.cluster.local

$ rkt enter 0ddca32a nslookup etcd-1
nslookup: can't resolve '(null)': Name does not resolve

Name:      etcd-1
Address 1: 10.3.0.22 etcd-1.default.svc.cluster.local

$ rkt enter 0ddca32a cat /etc/resolv.conf
# Generated by rkt

search default.svc.cluster.local svc.cluster.local cluster.local kube-system.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.3.0.10
options ndots:5
```

**Pull request closed without merging**
