### PR TITLE
[WIP] Add support for external load-balancer to access OpenStack APIs

### PR DESCRIPTION
**Pull request by Quentin-M**
On the high level, this allows to specify that a service/port should be
be exposed externally (to the cluster) on a specific host/port
(`<service>.<external_domain>:<external_port>`).
 
To do this, Ingress controllers are exposed through a service listening
on `<external_port>` on every nodes (NodePort). Any request to any 
node on that port will be forwarded to one of the Ingress
controller with the help of the Kubernetes' service load balancing
mechanism. The controller will in turn forward the request to the proper
Kubernetes service backing the OpenStack APIs, based on the request' host.

Multiplexing is host-based (`<service>`) rather than path-based (i.e. `<external_domain>:<external_port>/<service>`). Multiplexing on path is slightly trickier and less maintainable in my opinion. While it still requires DNS resolution anyways (right, a single domain instead of a wildcard domain), we can't simply strip the prefix off before passing the requests to the OpenStack APIs because some like to return back to the clients absolute paths to follow to continue the interaction (i.e. KeyStone). We'd have to pass the requests with the prefix and configure apache wsgi / pipelines to accept/understand prefixed requests.

The potential extra roundtrip between the node (NodePort) and the
Ingress controllers allows us to deploy the controllers in a
high-availability and scalable way, on a specific set of nodes, while
still being able to access them via any nodes. It also provides us the
guarantee of always accessing a ready/working controller as their
healths are monitored by Kubernetes and are behind a managed service.
If we would expose the controllers directly using a hostPort (which is
not currently supposed by the kubelet's CNI implementation) or using the
host network, an external regular DNS resolution may more likely lead us
to a dead/unavailable controller/node.

This PR includes [traefik](https://traefik.io/) as the Ingress controller but virtually any other controllers could be used (nginx, vulcan, haproxy, ...).

Reviews are much appreciated - this isn't a small change.

### CODE REVIEW

**Comment by Quentin-M** [comment]
Next step is to secure external endpoints using SSL/TLS.

**Comment by PiotrProkop** [comment]
Can we make this optional in Stackanetes ? Prepare an option in stackanetes.conf to deploy it or not ?

**Comment by Quentin-M** [comment]
Yes, that makes a lot of sense, I am implementing it into the [kpm repackage](https://github.com/Quentin-M/stackanetes-kpm). I'll demonstrate it and provide instructions soon.

**Comment by Quentin-M** [comment]
**Side note:** 

We might replace Traefik with any Ingress controllers. Nginx, for example, has the *advantage* that it doesn't forward requests to services but to pods directly. However, due to way Django generates absolute URLs for redirections and `refs` in the OpenStack APIs, the configuration of the nginx controller and OpenStack would have to be tweaked slightly. By default, Django doesn't use `X-Forwarded-For` headers but the `Host` header or a combination or `SERVER_NAME / SERVER_PORT` [[1]]. Every OpenStack clients passes the `Host` header and Traefik forwards it without modification, while nginx doesn't - replacing it with `$host`, which doesn't contain the port [[2]]. The issue is that Django will then generate URLs using the standard HTTP port - while the service must be accessed through our Ingress controller, on a custom port (30000-32767). The solution would be to tweak nginx to pass proper `X-Forwarded-For` headers depending on our NodePort configuration and then enable support for `X-Forwarded-For` on every OpenStack API services. A workaround is to replace `$host` by `$http_host`. Now, from few tests that I ran, with the default settings, it seems that Nginx is way slower than Traefik - so I don't believe that the effort is worth it. A good reason to replace Traefik by Nginx would be for SSL support for every OpenStack endpoints, but again, the URL generation assumes that `http` is the scheme, except if `SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')` is configured - and while it has been added to some services in Mitaka, it appears that certain OpenStack services won't support it until Newton.

[1]: https://docs.djangoproject.com/en/1.8/_modules/django/http/request/#HttpRequest.get_host
[2]: https://github.com/kubernetes/contrib/blob/2842513/ingress/controllers/nginx/nginx.tmpl#L231

**Comment by Quentin-M** [comment]
Closing in favor of #87.

**Pull request closed without merging**
